import random
a = random.randint(10, 10)
b = int(input("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"))
if (b == a):
    print("AAAAAAAAAAAAAAAAAAAAAAAAAA")
else:
    print("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")